---
- name: Loo LAMP-stack kaust
  file:
    path: "/home/{{ ansible_user }}/lamp-stack"
    state: directory
    mode: '0755'

- name: Kopeeri Docker Compose fail
  copy:
    src: "files/docker-compose.yml"
    dest: "/home/{{ ansible_user }}/lamp-stack/docker-compose.yml"
    mode: '0644'
