---
- name: Uuenda süsteem ja paketid
  apt:
    update_cache: yes
    upgrade: dist

- name: Installi vajalikud paketid
  apt:
    name:
      - htop
      - curl
      - vim
      - git
    state: present

- name: Loo uus kasutaja
  user:
    name: uusadmin
    password: "{{ 'P@ssw0rd123' | password_hash('sha512') }}"
    state: present
    shell: /bin/bash
