---
- name: Installi vajalikud sõltuvused
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Lisa Dockeri GPG võti
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

- name: Lisa Dockeri hoidla
  shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Uuenda apt cache ja installi Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Käivita Docker
  service:
    name: docker
    state: started
    enabled: yes
