---
- name: Seadista LAMP-stack serverid
  hosts: ubuntu_servers
  become: true

  roles:
    - common
    - docker
    - nginx
    - lamp  # <-- Parandatud siin, eelmine 'vars' rida oli vale

  vars:
    ansible_roles_path: "/home/janar1/ansible-project/roles"
