---
- name: Serveri seadistamine
  hosts: ubuntu_servers
  become: yes
  roles:
    - common
    - docker
    - nginx
#    - backup
    - logs
    - app
    - lamp
  vars: ansible_roles_path: "/home/janar1/ansible-project/roles"
